export const lista_veiculo = [
  {
    nome: 'M4 Sherman',
    pais_origem: 'EUA',
    status: 'Retirado',
    classificacao: 'Veiculo terrestre',
    tipo: 'Blindado medio',
    fabricante: 'American Locomotive Company, Baldwin Locomotive Works, Detroit Tank Arsenal, Federal Machine and Welder Company, Fisher Tank Arsenal, Ford Motor Company, Lima Locomotive Works, Pacific Car and Foundry Company, Pressed Steel Car Company, Pullman-Standard Car Company',
    utilizadores: "Argentina, Austrália, Bangladesh, Bélgica, Brasil, Canadá, Chile, Cuba, Dinamarca, Egito, Etiópia, França Livre, França, Grécia, Índia, Irã, Israel, Itália, Indonésia, Japão, Líbano, México, Alemanha nazista, Holanda, Nova Zelândia, Nicarágua, Paquistão, Paraguai, Peru, Filipinas, Polônia, Portugal, China, Taiwan, África do Sul, Coreia do Sul, União Soviética, Suécia, Síria, Uganda, Turquia, Reino Unido, Estados Unidos , Iugoslávia",
    variantes: 'M10 tank destroyer, M36 tank destroyer, M7 Priest self-propelled gun, M12 self-propelled gun, M40 self-propelled gun',
    quantidade_produzida: '49,234',
    quantidade_produzida_unidade: 'unidade',
    periodo_servico: '1942–2018',
    massa: '30.3–38.1',
    massa_unidade: 'toneladas',
    comprimento: '5.84–6.27',
    comprimento_unidade: 'metros',
    altura: '2.74–2.97',
    altura_unidade: 'metros',
    largura: '2.62',
    largura_unidade: 'metros',
    tripulacao: '5',
    custo_unitario: '44,556–64,455',
    custo_unitario_moeda: 'dollars',
    armamento: 'Armamento principal: 75mm gun M3 ou 76mm gun M1A1 ou 76mm gun M1A1C ou 76mm gun M1A2 ou 105mm howitzer M4. Armamento secundário: metralhadora pesada calibre .50 Browning M2HB, 2 metralhadoras calibre .30 Browning M1919A4',
  },
  {
    nome: 'T-34',
    pais_origem: 'União Soviética',
    status: 'servico_limitado',
    classificacao: 'Veículo terrestre',
    tipo: 'Blindado médio',
    fabricante: 'KhMDB',
    utilizadores: 'Cuba, Bósnia-Herzegovina, República do Congo, Guiné, Guiné-Bissau, Namíbia, Coreia do Norte, Iémen, Vietname, Afeganistão, Argélia, Albânia, Angola, Áustria, Bulgária, China, Chipre, Checoslováquia, Egipto, Guiné Equatorial, Etiópia , Finlândia, Alemanha nazista, Alemanha Oriental, Hungria, Reino da Itália, Iraque, Laos, Líbano, Líbia, Mali, Mongólia, Moçambique, Paquistão, Organização para a Libertação da Palestina, Polônia, Romênia (Reino da Romênia, República Socialista da Romênia), Somália, União Soviética, Sudão, Síria, Togo, Uganda, UNITA, Iêmen do Norte, Iêmen do Sul, Iugoslávia, Zimbábue',
    variantes: 'T-34-76 (Modelo 1940, Modelo 1941, Modelo 1942, Modelo 1943), T-34-85 (Modelo 1943, Modelo 1944, Modelo 1945, Modelo 1946, Modelo 1960, Modelo 1969), Lança-chamas (OT-34, OT-34-85, ATO-41, ATO-42, OT-34-76, OT-34-85), PT-1 mine roller tank, self-propelled howitzer (SU-122, T-122, T-34-122), tank destroyer(SU-85, SU-85M, SU-100, SU-122P, T-100), T-34-57, T-34-100, T-34-T armored recovery vehicle, SPK-5, SPK-5/10M, T-34-85CZ, T-34-TO, MT-34, VT-34, JT-34, T-34-85 75mm, T-34 firefighting vehicle, T-34 747(r), Self-propelled anti-aircraft gun (Flakpanzer T-34, Type 63, Type 65), T-34-85M1, T-34-85M2, Support vehicle(CW-34, WPT-34), T-34 150 mm gun, T-34 150mm gun, T-34-55, T-34 Teski Tenk Vozilo A (Heavy Tank Type A), T-34B',
    quantidade_produzida: '84,070 (35,120 T-34-76 e 48,950 T-34-85)',
    quantidade_produzida_unidade: 'unidade',
    periodo_servico: '1940 – presente',
    massa: '26.5 - 31.0',
    massa_unidade: 'toneladas',
    comprimento: '6.68',
    comprimento_unidade: 'metros',
    altura: '2.45',
    altura_unidade: 'metros',
    largura: '3.00',
    largura_unidade: 'metros',
    tripulacao: '	4 - 5',
    custo_unitario: '130,000–429,000',
    custo_unitario_moeda: 'rublos',
    armamento: 'Armamento principal: 76.2mm F-34 tank gun (T-34-76), 85mm ZiS-S-53 or 85mm D-5T tank gun (T-34-85). Armamento secundário: 2 Metralhadoras DT calibre 7.62 mm',
  }
];